web/src/main/java/cz/cvut/a4m36jee/jsf/AddPostBean.java
package cz.cvut.a4m36jee.jsf;


import cz.cvut.a4m36jee.semestralka.model.dto.PostDto;
import cz.cvut.a4m36jee.semestralka.service.PostService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;
import javax.validation.constraints.Size;
import java.util.Date;

/**
 * @author Stanislav Sazonov
 * @since 18.1.15.
 */
@ManagedBean
@RequestScoped
public class AddPostBean {

    @Inject
    private CurrentUserBean currentUserBean;

    @Inject
    private PostService postService;

    @Size(min = 1, message = "Title is not set")
    private String title;

    @Size(min = 1, message = "Text is not set")
    private String text;

    public String addPost(int topicId) {
        PostDto post = new PostDto();
        post.setDate(new Date());
        post.setTitle(title);
        post.setText(text);
        post.setUserId(currentUserBean.getUserDto().getId());
        post.setTopicId(topicId);

        postService.addPost(post);
        return "posts?topicId=" + topicId + "faces-redirect=true";

    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
}

web/src/main/java/cz/cvut/a4m36jee/jsf/AddTopicBean.java
package cz.cvut.a4m36jee.jsf;


import cz.cvut.a4m36jee.semestralka.model.dto.TopicDto;
import cz.cvut.a4m36jee.semestralka.service.TopicService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;
import javax.validation.constraints.Size;
import java.util.Date;

/**
 * @author Stanislav Sazonov
 * @since 18.1.15.
 */
@ManagedBean
@RequestScoped
public class AddTopicBean {

    @Inject
    private TopicService topicService;

    @Inject
    private CurrentUserBean user;

    @Size(min=1, message = "Name is not set.")
    private String name;

    public String createTopic(){
        TopicDto dto = new TopicDto();
        dto.setName(name);
        dto.setCreatedOn(new Date());
        dto.setCreatedById(user.getUserDto().getId());
        topicService.addTopic(dto);
        return "topics?faces-redirect=true";
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

web/src/main/java/cz/cvut/a4m36jee/jsf/AddUserBean.java
package cz.cvut.a4m36jee.jsf;

import cz.cvut.a4m36jee.semestralka.model.dto.UserDto;
import cz.cvut.a4m36jee.semestralka.service.UserService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ejb.EJBTransactionRolledbackException;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.validation.constraints.Size;

@ManagedBean
@RequestScoped
public class AddUserBean {

    private final Logger log = LoggerFactory.getLogger(AddUserBean.class);

    @Inject
    private UserService userService;

    @Size(min = 1, message = "Name is not set")
    private String name;

    @Size(min = 1, message = "Surname is not set")
    private String surname;

    @Size(min = 1, message = "Username is not set")
    private String username;

    @Size(min=5, message = "Email is not set correctly")
    private String email;

    @Size(min = 2, message = "Too short.")
    private String password;

    private UIComponent usernameInputField;

    public String createUser(){
        UserDto dto = new UserDto();
        dto.setName(name);
        dto.setSurname(surname);
        dto.setUsername(username);
        dto.setEmail(email);
        dto.setPassword(password);
        try {
            userService.addUser(dto);
        }
        catch(EJBTransactionRolledbackException ex){
            showDuplicateUsernameMessage();
        }
        return "/topics?faces-redirect=true";
    }

    private void showDuplicateUsernameMessage(){
        FacesMessage message = new FacesMessage("Username already exists.");
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(usernameInputField.getClientId(context), message);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public UIComponent getUsernameInputField() {
        return usernameInputField;
    }

    public void setUsernameInputField(UIComponent usernameInputField) {
        this.usernameInputField = usernameInputField;
    }
}

web/src/main/java/cz/cvut/a4m36jee/jsf/CurrentUserBean.java
package cz.cvut.a4m36jee.jsf;

import cz.cvut.a4m36jee.semestralka.model.dto.UserDto;
import cz.cvut.a4m36jee.semestralka.security.Role;
import cz.cvut.a4m36jee.semestralka.service.UserService;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.security.Principal;

/**
 * @author Tomas Milata
 * @since 1.2.15.
 */
@ManagedBean
@SessionScoped
@Named("currentUser")
public class CurrentUserBean {

    private UserDto userDto;

    @EJB
    private UserService userService;

    public UserDto getUserDto() {
        if (userDto == null) {
            Principal principal = FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal();
            if (principal != null) {
                userDto = userService.getByUsername(principal.getName());
            }
        }
        return userDto;
    }

    public boolean isAdmin() {
        return getUserDto().getRolesNames().contains(Role.ADMIN);
    }

    public boolean isModerator() {
        return getUserDto().getRolesNames().contains(Role.MODERATOR);
    }

    public boolean isUser() {
        return getUserDto().getRolesNames().contains(Role.USER);
    }

}

web/src/main/java/cz/cvut/a4m36jee/jsf/DeletePostBean.java
package cz.cvut.a4m36jee.jsf;

import cz.cvut.a4m36jee.semestralka.model.dto.PostDto;
import cz.cvut.a4m36jee.semestralka.service.PostService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;

@ManagedBean(name= "deletePost")
@RequestScoped
public class DeletePostBean {

    @Inject
    private PostService postService;

    public String delete(int postId, int topicId) {
        final PostDto postDto = new PostDto();
        postDto.setId(postId);
        postService.removePost(postDto);
        return "posts?topicId=" + topicId + "faces-redirect=true";
    }

}

web/src/main/java/cz/cvut/a4m36jee/jsf/DeleteTopicBean.java
package cz.cvut.a4m36jee.jsf;

import cz.cvut.a4m36jee.semestralka.model.dto.TopicDto;
import cz.cvut.a4m36jee.semestralka.service.TopicService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;

@ManagedBean(name= "deleteTopic")
@RequestScoped
public class DeleteTopicBean {

    @Inject
    private TopicService topicService;

    public String delete(int id) {
        final TopicDto topicDto = new TopicDto();
        topicDto.setId(id);
        topicService.deleteTopic(topicDto);
        return "topics?faces-redirect=true";
    }
	
}

web/src/main/java/cz/cvut/a4m36jee/jsf/LogoutBean.java
package cz.cvut.a4m36jee.jsf;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;

/**
 * @author Tomas Milata
 * @since 24.1.15.
 */
@ManagedBean
@RequestScoped
@Named("logout")
public class LogoutBean {

    public String logout() {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        ExternalContext externalContext = facesContext.getExternalContext();
        externalContext.invalidateSession();
        return "/topics?faces-redirect=true";
    }
}

web/src/main/java/cz/cvut/a4m36jee/jsf/PostsBean.java
package cz.cvut.a4m36jee.jsf;

import cz.cvut.a4m36jee.semestralka.model.dto.PostDto;
import cz.cvut.a4m36jee.semestralka.model.dto.TopicDto;
import cz.cvut.a4m36jee.semestralka.service.PostService;
import cz.cvut.a4m36jee.semestralka.service.TopicService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import java.util.List;
import java.util.Map;

/**
 * @author Tomas Milata
 * @since 15.1.15.
 */
@ManagedBean(name = "postsBean")
@SessionScoped
public class PostsBean {

    @Inject
    private PostService postService;

    @Inject
    private TopicService topicService;

    private String topicId;

    public Integer getTopicId() {
        if (topicId == null) {
            Map<String, String> params =
                    FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
            topicId = params.get("topicId");
        }
        return Integer.valueOf(topicId);
    }

    public void setTopicId(String topicId) {
        this.topicId = topicId;
    }

    public List<PostDto> getPosts() {

        final TopicDto topicDto = new TopicDto();
        topicDto.setId(getTopicId());
        return postService.getPostsForTopic(topicDto);
    }

    public TopicDto getTopic() {
        final TopicDto topicDto = new TopicDto();
        topicDto.setId(getTopicId());
        return topicService.getById(topicDto);
    }
}

web/src/main/java/cz/cvut/a4m36jee/jsf/TopicsBean.java
package cz.cvut.a4m36jee.jsf;

import cz.cvut.a4m36jee.semestralka.model.dto.TopicDto;
import cz.cvut.a4m36jee.semestralka.service.TopicService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.List;

/**
 * @author Stanislav Sazonov
 * @since 1.2.15.
 */
@ManagedBean
@RequestScoped
@Named("topics")
public class TopicsBean {

    private Logger log = LoggerFactory.getLogger(TopicsBean.class);

    @Inject
    private TopicService topicService;

    public List<TopicDto> getAllTopics() {
        List<TopicDto> topics = topicService.getAllTopics();
        log.info("topics size: {}", topics.size());
        return topics;
    }
}

web/src/main/java/cz/cvut/a4m36jee/jsf/UsersBean.java
package cz.cvut.a4m36jee.jsf;

import cz.cvut.a4m36jee.semestralka.model.dto.UserDto;
import cz.cvut.a4m36jee.semestralka.service.UserService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.List;

/**
 * @author Tomas Milata
 * @since 15.1.15.
 */
@ManagedBean
@RequestScoped
@Named("users")
public class UsersBean {

    @Inject
    private UserService userService;

    public List<UserDto> getAllUsers() {
        return userService.getAllUsers();
    }
}

web/src/main/webapp/addpost.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

	<h:head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	    <link href="${facesContext.externalContext.requestContextPath}/resources/css/styles.css" rel="stylesheet" type="text/css" />
	    <title>Forum</title>
	</h:head>

    <header id="header">
        <ui:insert name="header">
            <ui:include src="header.xhtml"/>
        </ui:insert>
    </header>

	<h1>Status</h1>
	
	<h3>"#{addPostBean.status}"</h3>
	
</html>

web/src/main/webapp/adduser.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="${facesContext.externalContext.requestContextPath}/resources/css/styles.css" rel="stylesheet" type="text/css" />
        <title>Forum</title>
    </h:head>

    <header id="header">
        <ui:insert name="header">
            <ui:include src="header.xhtml"/>
        </ui:insert>
    </header>

    <h1>Add user</h1>

    <h:form>
            <p>Name</p>
            <h:inputText id="nameInputText" value="#{addUserBean.name}"></h:inputText>
            <h:message class="validationMessage" for="nameInputText"/>

            <p>Surname</p>
            <h:inputText id="surnameInputText" value="#{addUserBean.surname}"></h:inputText>
            <h:message class="validationMessage" for="surnameInputText"/>

            <p>Username</p>
            <h:inputText id="usernameInputText" value="#{addUserBean.username}" binding="#{addUserBean.usernameInputField}"></h:inputText>
            <h:message class="validationMessage" for="usernameInputText"/>

            <p>Email</p>
            <h:inputText id="emailInputText" value="#{addUserBean.email}"></h:inputText>
            <h:message class="validationMessage" for="emailInputText"/>

            <p>Password</p>
            <h:inputSecret id="passwordInputText" value="#{addUserBean.password}"></h:inputSecret>
            <h:message class="validationMessage" for="passwordInputText"/>

            <h:commandButton value="Add user" action="#{addUserBean.createUser}"></h:commandButton>
    </h:form>
</html>

web/src/main/webapp/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
    Logged in as: #{currentUser.userDto.username}

    <h:form>
        <h:outputLink value="topics.xhtml" >Topics</h:outputLink>
        <h:outputLink rendered="#{currentUser.admin}" value="adduser.xhtml" >Add User</h:outputLink>
        <h:commandButton action="#{logout.logout}" value="Log Out"/>
    </h:form>
</ui:composition>

</html>

web/src/main/webapp/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>

    <h:outputLabel value="Please Log In."/>

    <form method="post" action="j_security_check" name="loginForm">
        <h:panelGrid columns="2">
            <h:outputLabel id="userNameLabel" for="j_username" value="Username:"/>
            <h:inputText id="j_username" autocomplete="off" />
            <h:outputLabel id="passwordLabel" for="j_password" value="Password:"/>
            <h:inputSecret id="j_password" autocomplete="off"/>
            <h:panelGroup>
                <h:commandButton type="submit" value="Login"/>
                <h:commandButton type="reset" value="Clear"/>
            </h:panelGroup>
        </h:panelGrid>
    </form>

    <!--<h3>Hint</h3>-->
    <!--<table>-->
        <!--<thead>-->
        <!--<tr>-->
            <!--<td>login</td>-->
            <!--<td>password</td>-->
            <!--<td>role</td>-->
        <!--</tr>-->
        <!--<tr>-->
            <!--<td>god</td>-->
            <!--<td>god</td>-->
            <!--<td>ADMIN</td>-->
        <!--</tr>-->
        <!--<tr>-->
            <!--<td>leos</td>-->
            <!--<td>leos</td>-->
            <!--<td>MODERATOR</td>-->
        <!--</tr>-->
        <!--<tr>-->
            <!--<td>pepa</td>-->
            <!--<td>pepa</td>-->
            <!--<td>USER</td>-->
        <!--</tr>-->
        <!--</thead>-->
    <!--</table>-->


</f:view>
</html>

web/src/main/webapp/login_failed.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <h:outputLabel value="Login Failed"/>
</f:view>
</html>

web/src/main/webapp/posts.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

	<h:head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	    <link href="${facesContext.externalContext.requestContextPath}/resources/css/styles.css" rel="stylesheet" type="text/css" />
	    <title>Forum</title>
	</h:head>

    <header id="header">
        <ui:insert name="header">
            <ui:include src="header.xhtml"/>
        </ui:insert>
    </header>

    <h2>Posts in topic</h2>
	<h1>#{postsBean.topic.name}</h1>

	<ui:repeat value="#{postsBean.posts}" var="p">
		<div>
			<b>#{p.title}</b><br/>
			#{p.text}<br/>
			#{p.date}<br/>
			#{p.username}
		</div>

		<h:form rendered="#{currentUser.admin || currentUser.moderator}">
			<h:commandButton action="#{deletePost.delete(p.id, postsBean.topicId)}" value="Delete"/>
		</h:form>
		
	</ui:repeat>
	
	<h1>Add Post</h1>

	<h:form>
		<p>Title:</p>
    	<h:inputText id="titleInputText" value="#{addPostBean.title}"/>
		<h:message class="validationMessage" for="titleInputText"/>
    	<p>Text:</p>
    	<h:inputTextarea cols="80" rows="20" id="textInputText" value="#{addPostBean.text}"/>
		<h:message class="validationMessage" for="textInputText"/>
    	<h:commandButton value="Add Post" action="#{addPostBean.addPost(postsBean.topicId)}">
            <f:param name="topicId" value="1"/>
        </h:commandButton>
    </h:form>
	
</html>

web/src/main/webapp/topics.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

	<h:head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	    <link href="${facesContext.externalContext.requestContextPath}/resources/css/styles.css" rel="stylesheet" type="text/css" />
	    <title>Forum</title>
	</h:head>

	<header id="header">
        <ui:insert name="header">
            <ui:include src="header.xhtml"/>
        </ui:insert>
    </header>

	<h1>Topics</h1>

	<ui:repeat value="#{topics.allTopics}" var="t">

		<div>
            Created: #{t.createdOn}
            <h:form>
                <h:link outcome="posts" includeViewParams="true">
                    <h3>#{t.name}</h3>
                    <f:param name="topicId" value="#{t.id}"/>
                </h:link>
                <h:commandButton rendered="#{currentUser.moderator || currentUser.admin}"
                                 action="#{deleteTopic.delete(t.id)}" value="Delete"/>
            </h:form>
        </div>

        <br/>

	</ui:repeat>


	<h:form rendered="#{currentUser.moderator || currentUser.admin}">
        <h1>Add topic</h1>
		<p>Name:</p>
    	<h:inputText id="titleInputText" value="#{addTopicBean.name}"/>
    	<h:commandButton value="Add" action="#{addTopicBean.createTopic}"/>
		<h:message class="validationMessage" for="titleInputText" id="titleMessage"/>
	</h:form>
	
</html>